/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author andre
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        FondoMenu = new javax.swing.JPanel();
        TituloMenu = new javax.swing.JLabel();
        BotonSalirMenu = new javax.swing.JButton();
        CargarArchivos = new javax.swing.JButton();
        ActualizarRepositorio = new javax.swing.JButton();
        ReporteDisponibilidadAlmacen = new javax.swing.JButton();
        RealizarPedido = new javax.swing.JButton();
        SolicitarProductosOtroAlmacen = new javax.swing.JButton();
        AgregarAlmacen = new javax.swing.JButton();
        AgregarCamino = new javax.swing.JButton();
        StockAlmacen = new javax.swing.JButton();
        MostrarGrafo = new javax.swing.JButton();
        SubTitulo = new javax.swing.JLabel();
        CerrarPrograma = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloMenu.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        TituloMenu.setText("Bienvenido a OrganizedChaos");

        BotonSalirMenu.setBackground(new java.awt.Color(255, 51, 51));
        BotonSalirMenu.setText("X");
        BotonSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirMenuActionPerformed(evt);
            }
        });

        CargarArchivos.setText("1. Cargar archivo");
        CargarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivosActionPerformed(evt);
            }
        });

        ActualizarRepositorio.setText("2. Actualizar Repositorio");

        ReporteDisponibilidadAlmacen.setText("3. Reportes de disponibilidad por almacen");

        RealizarPedido.setText("4. Realizar pedido");

        SolicitarProductosOtroAlmacen.setText("5. Solicitar productos a otro almacén");

        AgregarAlmacen.setText("6. Agregar un nuevo almacén");

        AgregarCamino.setText("7. Agregar un nuevo camino");

        StockAlmacen.setText("8. Gestión de stock de un almacén");

        MostrarGrafo.setText("9. Mostrar grafo");

        SubTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubTitulo.setText("Dale Click a la opcion que prefiera:");

        CerrarPrograma.setBackground(new java.awt.Color(255, 204, 204));
        CerrarPrograma.setText("CERRAR PROGRAMA");
        CerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoMenuLayout = new javax.swing.GroupLayout(FondoMenu);
        FondoMenu.setLayout(FondoMenuLayout);
        FondoMenuLayout.setHorizontalGroup(
            FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(TituloMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(284, 284, 284))
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(SubTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoMenuLayout.createSequentialGroup()
                        .addComponent(MostrarGrafo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CerrarPrograma))
                    .addComponent(StockAlmacen)
                    .addComponent(AgregarCamino)
                    .addComponent(AgregarAlmacen)
                    .addComponent(SolicitarProductosOtroAlmacen)
                    .addComponent(RealizarPedido)
                    .addComponent(ReporteDisponibilidadAlmacen)
                    .addComponent(ActualizarRepositorio)
                    .addComponent(CargarArchivos))
                .addGap(248, 248, 248))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSalirMenu)
                .addGap(202, 202, 202))
        );
        FondoMenuLayout.setVerticalGroup(
            FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BotonSalirMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TituloMenu)
                .addGap(18, 18, 18)
                .addComponent(SubTitulo)
                .addGap(14, 14, 14)
                .addComponent(CargarArchivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarRepositorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReporteDisponibilidadAlmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RealizarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolicitarProductosOtroAlmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarAlmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarCamino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockAlmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MostrarGrafo)
                    .addComponent(CerrarPrograma))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonSalirMenuActionPerformed

    private void CargarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarArchivosActionPerformed

    private void CerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarProgramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarRepositorio;
    private javax.swing.JButton AgregarAlmacen;
    private javax.swing.JButton AgregarCamino;
    private javax.swing.JButton BotonSalirMenu;
    private javax.swing.JButton CargarArchivos;
    private javax.swing.JButton CerrarPrograma;
    private javax.swing.JPanel FondoMenu;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton RealizarPedido;
    private javax.swing.JButton ReporteDisponibilidadAlmacen;
    private javax.swing.JButton SolicitarProductosOtroAlmacen;
    private javax.swing.JButton StockAlmacen;
    private javax.swing.JLabel SubTitulo;
    private javax.swing.JLabel TituloMenu;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
